---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: stop current running container
      command: docker stop my-container
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm my-container
      ignore_errors: yes

    - name: remove comingsoon-image
      command: docker rmi codewithamine/slider
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t codewithamine/slider .

    - name: Push Image to dockerhub
      command: docker push codewithamine/slider

    - name: run container
      command: docker run -d --name my-container -p 5000:80 codewithamine/slider
